str=input("enter string:")
print("capitalize:",str.capitalize())
print("lower:",str.lower())
print("upper:",str.upper())
print("islower:",str.islower())
print("isupper:",str.isupper())
print("isalphanumerice:",str.isalnum())
print("isdigit:",str.isdigit())
print("endswith:",str.endswith('e',0,len(str)))
print("starstwith:",str.startswith('r',0,len(str)))
print("count:",str.count('t',0,len(str)))
print("split:",str.split())
tem=str.split()
print("join:",':'.join(tem))
