str=input("enter string")
print("Capitalize:",str.capitalize())
print("Lower:",str.lower())
print("upper:",str.upper())
print("Isalphanumeric:",str.isalnum())
print("Isalpha:",str.isalpha())
print("Isdigit:",str.isdigit())
print("Isupper:",str.isupper())
print("IsLower:",str.islower())
print("Count::",str.count('e',0,len(str)))
print("Endswith:",str.endswith('n',2,7))
print("Startswith:",str.startswith('p',0,len(str)))
print("Split",str.split())
temp=str.split()
print("Join:",':'.join(temp))