n1=int(input("enter no1:"))
n2=int(input("enter no2:"))
n3=int(input("enter no3:"))
print("addition:",n1+n2)
print("substraction:",n2-n3)
print("multiplication:",n1*n3)
print("integer division:",n1//n2)
print("floating division:",n1/n2)
print("modulo:",n1%n2)